#!/bin/bash
# {{ ansible_managed }}
#############################################################################
# Copyright 2018 Ramon Fischer                                              #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#     http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

command_list=(apt-get awk sort wc unalias)
checkCommands()
{
    for current_command in "${command_list[@]}"
    do
        unalias ${current_command} 2>/dev/null
        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
        then
            /bin/echo -e "\e[01;31mCould not find command '${current_command}'.\e[0m"
            exit 1
        fi
    done
}

checkCommands

upgradeable_package_count=$(/usr/bin/apt-get --simulate --quiet=2 upgrade | /usr/bin/awk '{ print $2 }' | /usr/bin/sort -u | /usr/bin/wc -l)
removable_package_count=$(/usr/bin/apt-get --simulate --quiet=2 autoremove | /usr/bin/awk '{ print $2 }' | /usr/bin/sort -u | /usr/bin/wc -l)

if (( ${removable_package_count} > 0 ))
then
    /bin/echo -e "\e[01;33m[${removable_package_count}] dependency packages are not needed anymore! (execute as root: /usr/bin/apt-get autoremove)\e[0m"
fi

if (( ${upgradeable_package_count} > 0 ))
then
    /bin/echo -e "\e[01;31;5m[${upgradeable_package_count}] packages still need to be upgraded!\e[0m \e[01;31m(execute as root: /usr/bin/apt-get) upgrade)\e[0m"
fi
