#!/bin/bash
# {{ ansible_managed }}
#############################################################################
# Copyright 2018 Ramon Fischer                                              #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#     http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

command_list=(grep needrestart unalias)
checkCommands()
{
    for current_command in "${command_list[@]}"
    do
        unalias
        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
        then
            echo -e "\e[01;31mcould not find command '${current_command}'.\e[0m"
            exit 1
        fi
    done
}

checkCommands

DEBIAN_FRONTEND="noninteractive"
restart_daemon_count=$(/usr/sbin/needrestart -vnlr l 2>/dev/null | /bin/grep -c " restart ")

if (( ${restart_daemon_count} > 0 ))
then
    echo -e "\e[01;31;5m[${restart_daemon_count}] daemons are still using old libraries and need to be restarted!\e[0m \e[01;31m(execute as root: /usr/sbin/needrestart)\e[0m"
fi
