#!/bin/bash
# {{ ansible_managed }}
############################################################################
# Copyright 2018-2025 Ramon Fischer                                        #
#                                                                          #
# Licensed under the Apache License, Version 2.0 (the "License");          #
# you may not use this file except in compliance with the License.         #
# You may obtain a copy of the License at                                  #
#                                                                          #
#     http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                          #
# Unless required by applicable law or agreed to in writing, software      #
# distributed under the License is distributed on an "AS IS" BASIS,        #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
# See the License for the specific language governing permissions and      #
# limitations under the License.                                           #
############################################################################

command_list=(echo grep needrestart reboot shutdown unalias)
checkCommands()
{
    for current_command in "${command_list[@]}"
    do
        unalias ${current_command} 2>/dev/null
        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
        then
            /bin/echo -e "\e[01;31mCould not find command '${current_command}'.\e[0m"
            exit 1
        fi
    done
}

checkCommands

DEBIAN_FRONTEND="noninteractive"
need_reboot=$(/bin/echo | /usr/sbin/needrestart -vnk 2>/dev/null | /bin/grep "Pending kernel upgrade")

if [[ -n "${need_reboot}" ]]
then
    /bin/echo -e "\e[01;31mpending kernel upgrade:\e[0m \e[01;31;5ma reboot is required to use a newly installed kernel!\e[0m \e[01;31m(execute as root: /sbin/reboot)\e[0m"
fi
