---
#############################################################################
# Copyright 2018 Ramon Fischer                                              #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#     http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

- name: clone wemux repository
  git:
    repo: "https://github.com/zolrath/wemux"
    dest: "/usr/local/share/git/tmux/wemux/"
    force: "yes"
  tags:
    - tmux

- name: correct owner and group rights
  file:
    path: "/usr/local/share/git/tmux/wemux/"
    owner: "root"
    group: "staff"
    recurse: "yes"
    state: "directory"
  tags:
    - tmux

- name: copy binary, configuration file and man page file
  copy:
    src: "/usr/local/share/git/tmux/wemux/{{ item.COPY_SOURCE }}"
    dest: "/usr/local/{{ item.COPY_DESTINATION }}"
    owner: "root"
    group: "staff"
    mode: "{{ item.COPY_MODE }}"
    remote_src: "yes"
  with_items:
      - { COPY_SOURCE: "wemux", COPY_DESTINATION: "bin/", COPY_MODE: "0755" }
      - { COPY_SOURCE: "man/wemux.1", COPY_DESTINATION: "share/man/man1/", COPY_MODE: "0644" }
      - { COPY_SOURCE: "wemux.conf.example", COPY_DESTINATION: "etc/wemux.conf", COPY_MODE: "0644" }
  tags:
    - tmux

- name: edit configuration file
  lineinfile:
    path: "/usr/local/etc/wemux.conf"
    line: "host_list=({{ WEMUX_HOST_USER }})"
    insertafter: '## example: host_list=\(zolrath csagan brocksamson\)'
  tags:
    - tmux
