---
#############################################################################
# Copyright 2018 Ramon Fischer                                              #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#     http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

- name: create neovim directories
  file:
    path: "/{{ USERNAME }}/{{ item }}/"
    owner: "{{ USERNAME }}"
    group: "{{ USERNAME }}"
    mode: "0755"
    state: "directory"
  with_items:
    - ".config"
    - ".config/nvim"
    - ".config/nvim/tmp"
    - ".config/nvim/tmp/backup"
    - ".config/nvim/tmp/swp"
    - ".config/nvim/tmp/tmp"
    - ".config/nvim/tmp/undo"
  tags:
    - neovim

# pipelining has to be deactivated here
- name: let neovim install vundle plugins
  shell: "$(command -v nvim) +PluginUpdate +qall"
  vars:
    ansible_ssh_pipelining: "no"
  ignore_errors: "yes"
  tags:
    - neovim
